"""Replay a retargeted Jenga episode through robot-node command_ee_pose.

Use this for episodes generated by ``DAgger.jenga_retarget``. The standard
``7_replay_fr3.sh`` sends recorded joints, so it is not sufficient for Cartesian
retargeted poses.
"""

from __future__ import annotations

import argparse
import gzip
import json
import pickle
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple

import numpy as np
import zmq

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from franka_capture.gripper_fields import frame_gripper_target_width
from franka_replay.replay_fr3 import GripperDirectClient, extract_gripper_events


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("episode", help="Retargeted episode directory, metadata.json, or .pkl.gz")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=6002)
    parser.add_argument("--timeout-ms", type=int, default=2000)
    parser.add_argument("--execute", action="store_true", help="Actually send Cartesian poses to robot node")
    parser.add_argument("--skip-robot-check", action="store_true", help="Only inspect the file")
    parser.add_argument("--speed", type=float, default=1.0)
    parser.add_argument("--max-start-pos-delta", type=float, default=0.08)
    parser.add_argument("--max-start-rot-delta", type=float, default=0.35)
    parser.add_argument("--approach-start", action="store_true")
    parser.add_argument("--approach-start-step-m", type=float, default=0.01)
    parser.add_argument("--approach-start-hz", type=float, default=5.0)
    parser.add_argument("--gripper-host", default="127.0.0.1")
    parser.add_argument("--gripper-port", type=int, default=50054)
    parser.add_argument("--gripper-speed", type=float, default=0.1)
    parser.add_argument("--gripper-force", type=float, default=10.0)
    parser.add_argument("--gripper-event-delta", type=float, default=0.01)
    parser.add_argument("--gripper-hold-sec", type=float, default=2.0)
    parser.add_argument(
        "--no-stop-after-release",
        dest="stop_after_release",
        action="store_false",
        help="Continue the full retargeted episode after the release event.",
    )
    parser.add_argument(
        "--post-release-extra-frames",
        type=int,
        default=0,
        help="Extra Cartesian frames to execute after the release frame before returning home.",
    )
    parser.add_argument(
        "--no-home-after-release",
        dest="home_after_release",
        action="store_false",
        help="Do not move to calibrated home joints after the release event.",
    )
    parser.add_argument(
        "--home-joints-file",
        default=str(REPO_ROOT / "config" / "initial_joints.json"),
        help="Calibrated home joints JSON used after release.",
    )
    parser.add_argument(
        "--home-side",
        choices=("left", "right"),
        default="left",
        help="Side key in --home-joints-file. Jenga uses the left arm by default.",
    )
    parser.add_argument(
        "--home-gripper-width",
        type=float,
        default=None,
        help="Optional gripper width to keep while moving home. Default keeps the active width.",
    )
    parser.add_argument(
        "--no-align-release-to-place",
        action="store_true",
        help=(
            "Do not move the opening gripper event to the retargeted place anchor. "
            "By default, Jenga retargeted episodes release at the place anchor."
        ),
    )
    return parser.parse_args()


class RobotZMQCartesianClient:
    def __init__(self, host: str, port: int, timeout_ms: int) -> None:
        self.host = host
        self.port = port
        self.timeout_ms = timeout_ms
        self._context = zmq.Context()
        self._socket = self._context.socket(zmq.REQ)
        self._socket.setsockopt(zmq.RCVTIMEO, timeout_ms)
        self._socket.setsockopt(zmq.SNDTIMEO, timeout_ms)
        self._socket.setsockopt(zmq.LINGER, 0)
        self._socket.connect(f"tcp://{host}:{port}")

    def _request(self, method: str, args: Optional[Dict[str, Any]] = None) -> Any:
        request = {"method": method, "args": args or {}}
        try:
            self._socket.send(pickle.dumps(request))
            result = pickle.loads(self._socket.recv())
        except zmq.Again as exc:
            raise TimeoutError(f"Timed out waiting for robot node at tcp://{self.host}:{self.port}") from exc
        if isinstance(result, dict) and "error" in result:
            raise RuntimeError(f"Robot node returned error: {result['error']}")
        return result

    def num_dofs(self) -> int:
        return int(self._request("num_dofs"))

    def get_control_mode(self) -> str:
        mode = self._request("get_control_mode")
        return str(mode)

    def get_observations(self) -> Mapping[str, Any]:
        result = self._request("get_observations")
        if not isinstance(result, Mapping):
            raise RuntimeError(f"Expected observations dict, got {type(result)}")
        return result

    def move_to_joint_positions(
        self,
        joint_positions: np.ndarray,
        gripper_width: float,
        gripper_speed: float,
        gripper_force: float,
        restart_controller: bool = True,
    ) -> None:
        self._request(
            "move_to_joint_positions",
            {
                "joint_positions": np.asarray(joint_positions, dtype=float),
                "gripper_width": float(gripper_width),
                "gripper_speed": float(gripper_speed),
                "gripper_force": float(gripper_force),
                "restart_controller": bool(restart_controller),
            },
        )

    def command_ee_pose(
        self,
        pose_6d: np.ndarray,
        gripper_width: float,
        gripper_speed: float,
        gripper_force: float,
        update_gripper: bool,
    ) -> None:
        self._request(
            "command_ee_pose",
            {
                "pose_6d": np.asarray(pose_6d, dtype=float),
                "gripper_width": float(gripper_width),
                "gripper_speed": float(gripper_speed),
                "gripper_force": float(gripper_force),
                "update_gripper": bool(update_gripper),
            },
        )

    def close(self) -> None:
        self._socket.close(0)
        self._context.term()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        self.close()
        return False


def resolve_episode_file(path_like: str | Path) -> Path:
    path = Path(path_like).expanduser()
    if path.is_file():
        if path.name.endswith(".pkl.gz"):
            return path
        if path.name in {"metadata.json", "keyframes.json", "instruction.txt"}:
            return resolve_episode_file(path.parent)
        raise ValueError(f"Replay input file must end with .pkl.gz: {path}")
    if not path.is_dir():
        raise FileNotFoundError(f"Episode path does not exist: {path}")
    preferred = path / f"{path.name}.pkl.gz"
    if preferred.exists():
        return preferred
    candidates = sorted(path.glob("*.pkl.gz"))
    if len(candidates) == 1:
        return candidates[0]
    if not candidates:
        raise FileNotFoundError(f"No .pkl.gz file found in {path}")
    raise RuntimeError(f"Multiple .pkl.gz files found in {path}: {candidates}")


def load_episode(path_like: str | Path) -> Tuple[Path, Dict[str, Any], List[Mapping[str, Any]]]:
    episode_path = resolve_episode_file(path_like)
    with gzip.open(episode_path, "rb") as f:
        payload = pickle.load(f)
    if not isinstance(payload, dict):
        raise ValueError(f"Invalid payload in {episode_path}: expected dict")
    frames = payload.get("data") or payload.get("frames")
    if not isinstance(frames, list) or not frames:
        raise ValueError(f"Invalid payload in {episode_path}: missing non-empty data/frames")
    return episode_path, payload, frames


def extract_pose_trajectory(frames: Sequence[Mapping[str, Any]]) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    poses = np.asarray([frame["pose"] for frame in frames], dtype=float)
    timestamps = np.asarray([frame["timestamp"] for frame in frames], dtype=float)
    widths = np.asarray([frame_gripper_target_width(frame) for frame in frames], dtype=float)
    if poses.shape != (len(frames), 6):
        raise ValueError(f"Expected pose trajectory shape ({len(frames)}, 6), got {poses.shape}")
    if timestamps.shape != (len(frames),):
        raise ValueError("Invalid timestamp trajectory")
    if widths.shape != (len(frames),):
        raise ValueError("Invalid gripper width trajectory")
    if not np.all(np.isfinite(poses)):
        raise ValueError("Pose trajectory contains NaN or Inf")
    if not np.all(np.isfinite(timestamps)):
        raise ValueError("Timestamp trajectory contains NaN or Inf")
    if not np.all(np.isfinite(widths)):
        raise ValueError("Gripper width trajectory contains NaN or Inf")
    if np.any(np.diff(timestamps) < 0):
        raise ValueError("Episode timestamps must be monotonically nondecreasing")
    return poses, timestamps, widths


def pose_delta(current: np.ndarray, target: np.ndarray) -> Tuple[float, float, np.ndarray]:
    current = np.asarray(current, dtype=float).reshape(6)
    target = np.asarray(target, dtype=float).reshape(6)
    delta = target - current
    pos_delta = float(np.linalg.norm(delta[:3]))
    rot_delta = float(np.linalg.norm(wrap_angle_delta(delta[3:])))
    return pos_delta, rot_delta, delta


def wrap_angle_delta(delta: np.ndarray) -> np.ndarray:
    return (np.asarray(delta, dtype=float) + np.pi) % (2.0 * np.pi) - np.pi


def print_summary(
    episode_path: Path,
    payload: Mapping[str, Any],
    poses: np.ndarray,
    timestamps: np.ndarray,
    widths: np.ndarray,
    events: Sequence[Tuple[int, float, float]],
) -> None:
    duration = float(timestamps[-1] - timestamps[0]) if len(timestamps) > 1 else 0.0
    print(f"Episode: {episode_path}")
    print(f"Frames: {poses.shape[0]}")
    print(f"Duration: {duration:.3f} s")
    print(f"Retarget metadata present: {'yes' if 'dagger_retarget' in payload else 'no'}")
    print(f"Pose first: {np.array2string(poses[0], precision=4)}")
    print(f"Pose last:  {np.array2string(poses[-1], precision=4)}")
    print(f"XYZ range:  {np.array2string(poses[:, :3].max(axis=0) - poses[:, :3].min(axis=0), precision=4)}")
    print(
        "Gripper target width first/last/range: "
        f"{widths[0]:.6f} / {widths[-1]:.6f} / {float(widths.max() - widths.min()):.6f}"
    )
    print(f"Gripper direct events: {len(events)}")
    for event_idx, (frame_idx, timestamp, width) in enumerate(events[:12]):
        rel_time = float(timestamp - timestamps[0])
        print(f"  frame={frame_idx:04d}  t={rel_time:7.3f}s  target_width={width:.6f} m")
    if len(events) > 12:
        print(f"  ... {len(events) - 12} more events")


def align_release_events_to_place_anchor(
    events: Sequence[Tuple[int, float, float]],
    timestamps: np.ndarray,
    payload: Mapping[str, Any],
) -> List[Tuple[int, float, float]]:
    retarget = payload.get("dagger_retarget")
    if not isinstance(retarget, Mapping):
        return list(events)
    anchor_frames = retarget.get("anchor_frames")
    if not isinstance(anchor_frames, Mapping) or "place" not in anchor_frames:
        return list(events)
    place_frame = int(anchor_frames["place"])
    if place_frame < 0 or place_frame >= len(timestamps):
        return list(events)

    aligned: List[Tuple[int, float, float]] = []
    moved = False
    previous_width: Optional[float] = None
    for frame_idx, timestamp, width in events:
        output_frame = int(frame_idx)
        output_timestamp = float(timestamp)
        if previous_width is not None and float(width) > previous_width + 1e-4 and output_frame < place_frame:
            output_frame = place_frame
            output_timestamp = float(timestamps[place_frame])
            moved = True
        aligned.append((output_frame, output_timestamp, float(width)))
        previous_width = float(width)

    if not moved:
        return aligned

    # If two events land on the same frame, keep the later target width.
    deduped_by_frame: Dict[int, Tuple[int, float, float]] = {}
    for event in aligned:
        deduped_by_frame[event[0]] = event
    deduped = [deduped_by_frame[index] for index in sorted(deduped_by_frame)]
    print(
        "Aligned opening gripper event(s) to retargeted place anchor "
        f"frame {place_frame}."
    )
    return deduped


def retarget_place_frame(payload: Mapping[str, Any], trajectory_len: int) -> Optional[int]:
    retarget = payload.get("dagger_retarget")
    if not isinstance(retarget, Mapping):
        return None
    anchor_frames = retarget.get("anchor_frames")
    if not isinstance(anchor_frames, Mapping) or "place" not in anchor_frames:
        return None
    place_frame = int(anchor_frames["place"])
    if place_frame < 0 or place_frame >= trajectory_len:
        return None
    return place_frame


def find_release_event_frame(events: Sequence[Tuple[int, float, float]]) -> Optional[int]:
    previous_width: Optional[float] = None
    for frame_idx, _, width in sorted(events, key=lambda item: item[0]):
        width = float(width)
        if previous_width is not None and width > previous_width + 1e-4:
            return int(frame_idx)
        previous_width = width
    return None


def trim_trajectory_after_release(
    poses: np.ndarray,
    timestamps: np.ndarray,
    widths: np.ndarray,
    events: Sequence[Tuple[int, float, float]],
    payload: Mapping[str, Any],
    extra_frames: int,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, List[Tuple[int, float, float]], Optional[int]]:
    release_frame = find_release_event_frame(events)
    if release_frame is None:
        release_frame = retarget_place_frame(payload, len(poses))
    if release_frame is None:
        print("WARNING: could not identify release/place frame; full trajectory will be replayed.")
        return poses, timestamps, widths, list(events), None
    if extra_frames < 0:
        raise ValueError("--post-release-extra-frames must be nonnegative")
    trim_end = min(len(poses), int(release_frame) + 1 + int(extra_frames))
    trimmed_events = [event for event in events if int(event[0]) < trim_end]
    if trim_end < len(poses):
        print(
            "Truncated Cartesian replay after release/place frame "
            f"{release_frame}; executing {trim_end}/{len(poses)} frames."
        )
    return poses[:trim_end], timestamps[:trim_end], widths[:trim_end], trimmed_events, int(release_frame)


def load_home_joints(path_like: str | Path, side: str) -> np.ndarray:
    path = Path(path_like).expanduser()
    with path.open("r", encoding="utf-8") as f:
        payload = json.load(f)
    entry = payload.get(side)
    if not isinstance(entry, Mapping) or "joints" not in entry:
        raise KeyError(f"No calibrated {side!r} joints in {path}")
    joints = np.asarray(entry["joints"], dtype=float)
    if joints.shape != (7,):
        raise ValueError(f"Expected 7 home joints for {side!r}, got shape {joints.shape}")
    if not np.all(np.isfinite(joints)):
        raise ValueError(f"Home joints for {side!r} contain NaN or Inf")
    return joints


def move_home_after_release(
    client: RobotZMQCartesianClient,
    home_joints: np.ndarray,
    gripper_width: float,
    gripper_speed: float,
    gripper_force: float,
) -> None:
    print(f"Moving to calibrated home joints: {np.array2string(home_joints, precision=4)}")
    client.move_to_joint_positions(
        home_joints,
        gripper_width=gripper_width,
        gripper_speed=gripper_speed,
        gripper_force=gripper_force,
        restart_controller=True,
    )
    print("Reached calibrated home joints.")


def check_robot_start(client: RobotZMQCartesianClient, poses: np.ndarray, args: argparse.Namespace) -> Dict[str, Any]:
    num_dofs = client.num_dofs()
    mode = client.get_control_mode()
    observations = client.get_observations()
    current_pose = np.asarray(observations.get("ee_pose_euler"), dtype=float).reshape(6)
    target_pose = np.asarray(poses[0], dtype=float).reshape(6)
    pos_delta, rot_delta, delta = pose_delta(current_pose, target_pose)
    print(f"Robot node: tcp://{client.host}:{client.port}")
    print(f"Robot DOFs: {num_dofs}")
    print(f"Robot control mode: {mode}")
    print(f"Current EE pose: {np.array2string(current_pose, precision=4)}")
    print(f"Target frame 0 pose: {np.array2string(target_pose, precision=4)}")
    print(f"Start position delta: {pos_delta:.6f} m")
    print(f"Start rotation delta norm: {rot_delta:.6f} rad")
    if mode != "ee":
        message = (
            "Cartesian replay needs the robot node launched with --control-mode ee. "
            "Start 3_launch_node.sh with the same port plus --control-mode ee before executing."
        )
        if args.execute:
            raise RuntimeError(message)
        print(f"WARNING: {message}")
    if pos_delta > args.max_start_pos_delta or rot_delta > args.max_start_rot_delta:
        message = (
            f"Start pose delta exceeds limits: pos {pos_delta:.6f}>{args.max_start_pos_delta:.6f} "
            f"or rot {rot_delta:.6f}>{args.max_start_rot_delta:.6f}."
        )
        if args.execute and not args.approach_start:
            raise RuntimeError(message + " Move close to frame 0 or pass --approach-start.")
        print("WARNING: " + message)
    return {
        "mode": mode,
        "current_pose": current_pose,
        "target_pose": target_pose,
        "pos_delta": pos_delta,
        "rot_delta": rot_delta,
        "delta": delta,
    }


def approach_start_pose(
    client: RobotZMQCartesianClient,
    start_info: Mapping[str, Any],
    target_width: float,
    step_m: float,
    hz: float,
    gripper_speed: float,
    gripper_force: float,
) -> None:
    def try_command(pose: np.ndarray, label: str, required: bool) -> bool:
        try:
            client.command_ee_pose(
                pose,
                gripper_width=target_width,
                gripper_speed=gripper_speed,
                gripper_force=gripper_force,
                update_gripper=False,
            )
            return True
        except RuntimeError as exc:
            if "IK failed" not in str(exc):
                raise
            message = f"IK failed during approach-start {label}: {np.array2string(pose, precision=4)}"
            if required:
                raise RuntimeError(message) from exc
            print("WARNING: " + message + " ; skipping this interpolation point.")
            return False

    if step_m <= 0:
        raise ValueError("--approach-start-step-m must be positive")
    if hz <= 0:
        raise ValueError("--approach-start-hz must be positive")
    current = np.asarray(start_info["current_pose"], dtype=float).reshape(6)
    target = np.asarray(start_info["target_pose"], dtype=float).reshape(6)
    pos_delta = float(start_info["pos_delta"])
    rot_delta = wrap_angle_delta(target[3:] - current[3:])
    steps = max(1, int(np.ceil(pos_delta / step_m)))
    period = 1.0 / float(hz)
    rot_steps = max(1, int(np.ceil(float(np.linalg.norm(rot_delta)) / 0.05)))
    print(
        "Approaching Cartesian frame 0: "
        f"pos_delta={pos_delta:.6f} m, xyz_steps={steps}, rot_steps={rot_steps}, hz={hz:.3f}"
    )

    # Keep the current orientation while moving in XYZ. This avoids IK failures
    # from Euler interpolation near the +/-pi boundary before the robot is close
    # to the first replay frame.
    for step_idx in range(1, steps + 1):
        t0 = time.monotonic()
        alpha = step_idx / steps
        pose = current.copy()
        pose[:3] = current[:3] + alpha * (target[:3] - current[:3])
        try_command(pose, f"xyz {step_idx}/{steps}", required=False)
        sleep_s = max(0.0, period - (time.monotonic() - t0))
        if sleep_s:
            time.sleep(sleep_s)

    for step_idx in range(1, rot_steps + 1):
        t0 = time.monotonic()
        alpha = step_idx / rot_steps
        pose = target.copy()
        if step_idx < rot_steps:
            pose[3:] = current[3:] + alpha * rot_delta
            required = False
        else:
            required = True
        try_command(pose, f"orientation {step_idx}/{rot_steps}", required=required)
        sleep_s = max(0.0, period - (time.monotonic() - t0))
        if sleep_s:
            time.sleep(sleep_s)


def replay_cartesian(
    client: RobotZMQCartesianClient,
    gripper_client: GripperDirectClient,
    poses: np.ndarray,
    timestamps: np.ndarray,
    widths: np.ndarray,
    events: Sequence[Tuple[int, float, float]],
    speed: float,
    gripper_speed: float,
    gripper_force: float,
    gripper_hold_sec: float,
) -> None:
    if speed <= 0:
        raise ValueError("--speed must be positive")
    if gripper_hold_sec < 0:
        raise ValueError("--gripper-hold-sec must be nonnegative")
    events_by_frame = {frame_idx: width for frame_idx, _, width in events}
    active_width = float(events[0][2]) if events else float(widths[0])
    start_wall = time.monotonic()
    start_episode = float(timestamps[0])
    timeline_delay = 0.0
    total = len(poses)
    print(
        "Executing Cartesian replay. "
        f"speed={speed}, gripper_speed={gripper_speed}, gripper_force={gripper_force}, "
        f"gripper_hold_sec={gripper_hold_sec}. Press Ctrl+C to interrupt."
    )
    for idx, pose in enumerate(poses):
        target_elapsed = (float(timestamps[idx]) - start_episode) / speed
        while True:
            remaining = start_wall + target_elapsed + timeline_delay - time.monotonic()
            if remaining <= 0:
                break
            time.sleep(min(remaining, 0.01))

        client.command_ee_pose(
            pose,
            gripper_width=active_width,
            gripper_speed=gripper_speed,
            gripper_force=gripper_force,
            update_gripper=False,
        )
        event_width = events_by_frame.get(idx)
        if event_width is not None:
            gripper_client.goto_width(event_width, gripper_speed, gripper_force)
            active_width = float(event_width)
            print(f"Sent gripper event at frame {idx + 1}/{total}: target_width={event_width:.6f} m")
            if gripper_hold_sec > 0:
                time.sleep(gripper_hold_sec)
                timeline_delay += gripper_hold_sec
        if idx == 0 or idx == total - 1 or idx % 50 == 0:
            print(f"Sent Cartesian frame {idx + 1}/{total}")


def main() -> int:
    args = parse_args()
    if args.execute and args.skip_robot_check:
        raise ValueError("--skip-robot-check cannot be used with --execute")

    episode_path, payload, frames = load_episode(args.episode)
    poses, timestamps, widths = extract_pose_trajectory(frames)
    events = extract_gripper_events(widths, timestamps, args.gripper_event_delta)
    if not args.no_align_release_to_place:
        events = align_release_events_to_place_anchor(events, timestamps, payload)
    release_frame: Optional[int] = None
    if args.stop_after_release:
        poses, timestamps, widths, events, release_frame = trim_trajectory_after_release(
            poses,
            timestamps,
            widths,
            events,
            payload,
            args.post_release_extra_frames,
        )
    else:
        release_frame = find_release_event_frame(events)
    print_summary(episode_path, payload, poses, timestamps, widths, events)
    if args.home_after_release:
        if release_frame is None:
            print("WARNING: home-after-release requested but no release/place frame was identified.")
        else:
            print(
                f"Home after release: side={args.home_side}, "
                f"joints_file={Path(args.home_joints_file).expanduser()}"
            )

    if args.skip_robot_check:
        print("Robot check skipped. No command was sent.")
        return 0

    with RobotZMQCartesianClient(args.host, args.port, args.timeout_ms) as client:
        start_info = check_robot_start(client, poses, args)
        if not args.execute:
            print("Dry-run only. Add --execute to send Cartesian poses to the robot.")
            return 0
        if args.approach_start:
            approach_start_pose(
                client,
                start_info,
                float(widths[0]),
                args.approach_start_step_m,
                args.approach_start_hz,
                args.gripper_speed,
                args.gripper_force,
            )
        with GripperDirectClient(args.gripper_host, args.gripper_port, args.timeout_ms) as gripper_client:
            current_width = gripper_client.get_width()
            print(
                f"Direct gripper server: {args.gripper_host}:{args.gripper_port}, "
                f"current_width={current_width:.6f} m"
            )
            active_home_width = float(widths[0])
            if events:
                active_home_width = float(events[-1][2])
            if args.home_gripper_width is not None:
                active_home_width = float(args.home_gripper_width)
            replay_cartesian(
                client,
                gripper_client,
                poses,
                timestamps,
                widths,
                events,
                args.speed,
                args.gripper_speed,
                args.gripper_force,
                args.gripper_hold_sec,
            )
            if args.home_after_release and release_frame is not None:
                home_joints = load_home_joints(args.home_joints_file, args.home_side)
                move_home_after_release(
                    client,
                    home_joints,
                    active_home_width,
                    args.gripper_speed,
                    args.gripper_force,
                )
    print("Cartesian replay finished.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("\nReplay interrupted by user.", file=sys.stderr)
        raise SystemExit(130)
